definitions:
  handler.Request:
    properties:
      active:
        type: boolean
      age:
        type: integer
      creationDate:
        type: string
      email:
        type: string
      height:
        type: number
      id:
        type: string
      lastName:
        type: string
      name:
        type: string
    required:
    - active
    - age
    - email
    - height
    - lastName
    type: object
  web.Response:
    properties:
      code:
        type: string
      data: {}
      error:
        type: string
    type: object
info:
  contact:
    name: Adriana Echeverri
    url: http://www.swagger.io/support
  description: This is a simple API that manages users in an ecommerce page.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos-y-condiciones
  title: MELI Bootcamp User - API
  version: "1.0"
paths:
  /users:
    get:
      description: get all users
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List users
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not found products
          schema:
            $ref: '#/definitions/web.Response'
      summary: Show all users
      tags:
      - Users
    post:
      consumes:
      - application/json
      parameters:
      - description: token requerido
        in: header
        name: token
        required: true
        type: integer
      - description: User to Store
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
      summary: Store user
      tags:
      - Users
  /users/{id}:
    delete:
      parameters:
      - description: Product id
        in: path
        name: id
        required: true
        type: string
      - description: Token
        in: header
        name: token
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
      summary: Delete user
      tags:
      - Users
    get:
      description: get user by its id
      parameters:
      - description: ID user
        in: path
        name: id
        required: true
        type: string
      - description: token
        in: header
        name: token
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: user
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not found products
          schema:
            $ref: '#/definitions/web.Response'
      summary: Show user of specified id
      tags:
      - Users
    patch:
      consumes:
      - application/json
      description: This endpoint update field last name and age from an user
      parameters:
      - description: Token header
        in: header
        name: token
        required: true
        type: integer
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User last name and age
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/handler.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
      summary: Update last name and age of user
      tags:
      - Users
    put:
      consumes:
      - application/json
      parameters:
      - description: Id user
        in: path
        name: id
        required: true
        type: string
      - description: Token
        in: header
        name: token
        type: integer
      - description: User to update
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
      summary: Update user
      tags:
      - Users
swagger: "2.0"
